calculator: main.o addition.o Division.o Print.o
		g++ main.o addition.o Division.o Print.o -o calculator

main.o: main.cpp
		g++ -c main.cpp

Adition.o: addition.cpp
		   g++ -c addition.cpp

Division.o: Division.cpp
			g++ -c Division.cpp

Print.o: Print.cpp
		 g++ -c Print.cpp